# CONEXION A SUPABASE - SESSION POOLER
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.aykpkojbyebogehxhjne
spring.datasource.password=lafondarestaurante
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA CONFIGURACION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DESHABILITAR DEVTOOLS
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# LOGGING
logging.level.pe.edu.utp.restaurante=DEBUG