-- INSTALACION COMPLETA: esquema nuevo y carta real. NO ejecutar sobre una base existente.
-- Ejecuta este archivo SOLO, o los archivos 01 y 02 por separado; no ambas rutas.
BEGIN;
-- LA FONDA - INSTALACION NUEVA, PostgreSQL 14+.
-- Ejecutar en una base VACIA / proyecto Supabase NUEVO. No es una migracion.
-- No elimina datos. Si existe una tabla homonima, falla y revierte la transaccion.
-- No crea usuarios PostgreSQL ni contiene contrasenas o claves de Supabase.
SET LOCAL search_path = public;
SET LOCAL TIME ZONE 'America/Lima';

CREATE TABLE categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) NOT NULL UNIQUE CHECK (btrim(nombre) <> ''),
    descripcion varchar(255), activo boolean NOT NULL DEFAULT true,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT localtimestamp
);
CREATE UNIQUE INDEX uq_categoria_nombre_ci ON categorias (lower(btrim(nombre)));

CREATE TABLE usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni varchar(8) NOT NULL UNIQUE CHECK (dni ~ '^[0-9]{8}$'),
    nombre varchar(255) NOT NULL CHECK (length(btrim(nombre)) BETWEEN 1 AND 100),
    apellido varchar(255) NOT NULL CHECK (length(btrim(apellido)) BETWEEN 1 AND 100),
    email varchar(255),
    password varchar(255), -- Solo hash BCrypt; NULL para MOZO.
    rol varchar(255) NOT NULL CHECK (rol IN ('MOZO','CAJERO','ADMIN','COCINERO')),
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp,
    CONSTRAINT ck_usuario_email CHECK (email IS NULL OR (length(email) <= 254 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$')),
    CONSTRAINT ck_usuario_clave_rol CHECK (
        (rol = 'MOZO' AND password IS NULL) OR
        (rol <> 'MOZO' AND password IS NOT NULL AND password ~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$')
    )
);
CREATE UNIQUE INDEX uq_usuario_email_ci ON usuarios (lower(btrim(email))) WHERE email IS NOT NULL;

CREATE TABLE mesas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero integer NOT NULL UNIQUE CHECK (numero > 0),
    capacidad integer NOT NULL DEFAULT 4 CHECK (capacidad BETWEEN 1 AND 100),
    estado varchar(255) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado IN ('DISPONIBLE','OCUPADA','RESERVADA')),
    created_at timestamp NOT NULL DEFAULT localtimestamp
);

CREATE TABLE clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(255) NOT NULL CHECK (btrim(nombre) <> ''),
    apellido varchar(255) NOT NULL CHECK (btrim(apellido) <> ''),
    email varchar(255) NOT NULL CHECK (length(email) <= 254 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'),
    password varchar(255), -- Hash local, nunca la clave de Gmail. NULL con OAuth.
    telefono varchar(255), direccion_default varchar(255),
    activo boolean NOT NULL DEFAULT true,
    email_verificado_at timestamptz,
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp,
    CONSTRAINT ck_cliente_hash CHECK (password IS NULL OR password ~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$')
);
CREATE UNIQUE INDEX uq_cliente_email_ci ON clientes (lower(btrim(email)));

CREATE TABLE clientes_identidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    proveedor varchar(30) NOT NULL CHECK (proveedor IN ('GOOGLE','SUPABASE')),
    sujeto varchar(255) NOT NULL CHECK (btrim(sujeto) <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (proveedor, sujeto), UNIQUE (cliente_id, proveedor)
);
CREATE TABLE clientes_direcciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    etiqueta varchar(50) NOT NULL DEFAULT 'Casa',
    direccion text NOT NULL CHECK (btrim(direccion) <> ''),
    distrito varchar(100), referencia text,
    latitud numeric(9,6) CHECK (latitud BETWEEN -90 AND 90),
    longitud numeric(9,6) CHECK (longitud BETWEEN -180 AND 180),
    predeterminada boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_direccion_principal ON clientes_direcciones(cliente_id) WHERE predeterminada;
CREATE INDEX ix_direcciones_cliente ON clientes_direcciones(cliente_id);
CREATE TABLE clientes_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    tipo varchar(30) NOT NULL CHECK (tipo IN ('VERIFICAR_EMAIL','RECUPERAR_CLAVE','SESION')),
    token_hash varchar(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    expires_at timestamptz NOT NULL, used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX ix_tokens_cliente ON clientes_tokens(cliente_id);
CREATE INDEX ix_tokens_expiracion ON clientes_tokens(expires_at);

CREATE TABLE platos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(255) NOT NULL CHECK (btrim(nombre) <> ''),
    descripcion varchar(255),
    precio numeric(10,2) NOT NULL CHECK (precio > 0),
    categoria_id bigint NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
    tiempo_preparacion integer CHECK (tiempo_preparacion >= 0),
    disponible boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp
);
CREATE UNIQUE INDEX uq_plato_categoria_nombre_ci ON platos(categoria_id, lower(btrim(nombre)));
CREATE INDEX ix_platos_carta ON platos(categoria_id, disponible);
CREATE TABLE platos_imagenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plato_id bigint NOT NULL REFERENCES platos(id) ON DELETE CASCADE,
    storage_key text NOT NULL CHECK (btrim(storage_key) <> ''),
    url_publica text CHECK (url_publica IS NULL OR url_publica LIKE 'https://%'),
    alt_text varchar(255), orden integer NOT NULL DEFAULT 0,
    principal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (plato_id, storage_key)
);
CREATE INDEX ix_imagenes_plato ON platos_imagenes(plato_id);
CREATE UNIQUE INDEX uq_imagen_principal ON platos_imagenes(plato_id) WHERE principal;

CREATE TABLE pedidos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(20) NOT NULL UNIQUE,
    tipo varchar(20) NOT NULL DEFAULT 'LOCAL' CHECK (tipo IN ('LOCAL','DELIVERY','RECOJO')),
    origen varchar(20) NOT NULL DEFAULT 'PRESENCIAL' CHECK (origen IN ('PRESENCIAL','WEB')),
    mesa_id bigint REFERENCES mesas(id) ON DELETE RESTRICT,
    usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
    cliente_id bigint REFERENCES clientes(id) ON DELETE RESTRICT,
    cliente_nombre varchar(255), cliente_telefono varchar(20), direccion_entrega varchar(255),
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_PROCESO','LISTO','TERMINADO','ENTREGADO','CANCELADO')),
    subtotal numeric(38,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0), -- Base SIN IGV.
    total numeric(38,2) NOT NULL DEFAULT 0 CHECK (total >= 0), -- Total final CON IGV.
    igv numeric(38,2) NOT NULL DEFAULT 0 CHECK (igv >= 0),
    tasa_igv numeric(5,4) NOT NULL DEFAULT 0.18 CHECK (tasa_igv BETWEEN 0 AND 1),
    costo_envio numeric(10,2) NOT NULL DEFAULT 0 CHECK (costo_envio >= 0),
    descuento numeric(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    observacion_extra varchar(255), cerrado boolean NOT NULL DEFAULT false,
    mesa_numero integer, mozo_nombre varchar(255), -- Instantaneas de identificacion.
    clave_idempotencia uuid UNIQUE, -- El futuro backend debe enviar una clave estable por intento de pedido web.
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp,
    fecha_cierre timestamp,
    CONSTRAINT ck_pedido_local CHECK (tipo <> 'LOCAL' OR mesa_id IS NOT NULL),
    CONSTRAINT ck_pedido_web CHECK (origen <> 'WEB' OR (cliente_id IS NOT NULL AND clave_idempotencia IS NOT NULL AND tipo IN ('DELIVERY','RECOJO'))),
    CONSTRAINT ck_delivery_direccion CHECK (tipo <> 'DELIVERY' OR (direccion_entrega IS NOT NULL AND btrim(direccion_entrega) <> ''))
);
CREATE INDEX ix_pedidos_mesa_estado ON pedidos(mesa_id, estado);
CREATE INDEX ix_pedidos_cocina ON pedidos(estado, created_at);
CREATE INDEX ix_pedidos_cliente ON pedidos(cliente_id, created_at DESC);
CREATE INDEX ix_pedidos_usuario ON pedidos(usuario_id);
CREATE UNIQUE INDEX uq_mesa_pedido_abierto ON pedidos(mesa_id)
    WHERE mesa_id IS NOT NULL AND estado IN ('PENDIENTE','EN_PROCESO','LISTO','TERMINADO');

CREATE TABLE pedido_detalles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    plato_id bigint NOT NULL REFERENCES platos(id) ON DELETE RESTRICT,
    cantidad integer NOT NULL CHECK (cantidad > 0),
    precio_unitario numeric(10,2) NOT NULL CHECK (precio_unitario > 0),
    subtotal numeric(10,2) NOT NULL CHECK (subtotal = round(cantidad * precio_unitario, 2)),
    plato_nombre varchar(255), -- Instantanea; no se lee el precio actual al reimprimir.
    observacion_extra varchar(255),
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_PROCESO','LISTO','ENTREGADO','CANCELADO')),
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp
);
CREATE INDEX ix_detalles_pedido ON pedido_detalles(pedido_id);
CREATE INDEX ix_detalles_plato ON pedido_detalles(plato_id);

CREATE TABLE pagos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL UNIQUE REFERENCES pedidos(id) ON DELETE RESTRICT,
    monto numeric(10,2) NOT NULL CHECK (monto > 0),
    metodo varchar(20) NOT NULL CHECK (metodo IN ('EFECTIVO','TARJETA','YAPE','TRANSFERENCIA','OTRO','ONLINE')),
    referencia varchar(50),
    usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
    proveedor varchar(50), transaccion_externa varchar(255),
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    UNIQUE(proveedor, transaccion_externa)
);
CREATE INDEX ix_pagos_fecha ON pagos(created_at DESC);
CREATE INDEX ix_pagos_cajero ON pagos(usuario_id);
CREATE TABLE pagos_intentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    proveedor varchar(50) NOT NULL, referencia_externa varchar(255),
    clave_idempotencia uuid NOT NULL UNIQUE,
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','APROBADO','RECHAZADO','EXPIRADO')),
    monto numeric(10,2) NOT NULL CHECK (monto > 0), moneda char(3) NOT NULL DEFAULT 'PEN',
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (proveedor, referencia_externa)
);
CREATE INDEX ix_intentos_pedido ON pagos_intentos(pedido_id);
CREATE TABLE pedidos_entregas (
    pedido_id bigint PRIMARY KEY REFERENCES pedidos(id) ON DELETE RESTRICT,
    estado varchar(25) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','PREPARANDO','LISTO','EN_CAMINO','ENTREGADO','CANCELADO')),
    direccion_snapshot text, receptor varchar(150), telefono varchar(30),
    programado_para timestamptz, entregado_at timestamptz,
    instrucciones text, updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE pedido_eventos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    estado_anterior varchar(20), estado_nuevo varchar(20) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_eventos_pedido ON pedido_eventos(pedido_id, created_at);

CREATE TABLE resenas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    plato_id bigint REFERENCES platos(id) ON DELETE RESTRICT,
    calificacion smallint NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario text CHECK (length(comentario) <= 3000),
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','PUBLICADA','OCULTA')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_resena_pedido ON resenas(cliente_id, pedido_id) WHERE plato_id IS NULL;
CREATE UNIQUE INDEX uq_resena_plato ON resenas(cliente_id, pedido_id, plato_id) WHERE plato_id IS NOT NULL;
CREATE INDEX ix_resenas_publicadas ON resenas(plato_id, estado);
CREATE INDEX ix_resenas_pedido ON resenas(pedido_id);
CREATE TABLE resenas_imagenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resena_id bigint NOT NULL REFERENCES resenas(id) ON DELETE CASCADE,
    storage_key text NOT NULL, alt_text varchar(255),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_resena_imagenes ON resenas_imagenes(resena_id);

-- Normalizacion y auditoria compatibles con los LocalDateTime actuales de Java.
CREATE FUNCTION normalizar_persona() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.email := nullif(lower(btrim(NEW.email)), '');
    NEW.updated_at := localtimestamp;
    RETURN NEW;
END $$;
CREATE TRIGGER usuarios_normalizar BEFORE INSERT OR UPDATE ON usuarios FOR EACH ROW EXECUTE FUNCTION normalizar_persona();
CREATE TRIGGER clientes_normalizar BEFORE INSERT OR UPDATE ON clientes FOR EACH ROW EXECUTE FUNCTION normalizar_persona();

CREATE FUNCTION pedido_preparar() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.estado IN ('ENTREGADO','CANCELADO') THEN
        RAISE EXCEPTION 'Un pedido finalizado no se modifica';
    END IF;
    NEW.subtotal := round(NEW.total / (1 + NEW.tasa_igv), 2);
    NEW.igv := NEW.total - NEW.subtotal;
    NEW.updated_at := localtimestamp;
    IF TG_OP = 'INSERT' THEN
        IF NEW.mesa_id IS NOT NULL THEN SELECT numero INTO NEW.mesa_numero FROM mesas WHERE id = NEW.mesa_id; END IF;
        IF NEW.usuario_id IS NOT NULL THEN SELECT nombre || ' ' || apellido INTO NEW.mozo_nombre FROM usuarios WHERE id = NEW.usuario_id; END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER pedido_preparar BEFORE INSERT OR UPDATE ON pedidos FOR EACH ROW EXECUTE FUNCTION pedido_preparar();

CREATE FUNCTION pedido_registrar_evento() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO pedido_eventos(pedido_id, estado_nuevo) VALUES (NEW.id, NEW.estado);
    ELSIF NEW.estado IS DISTINCT FROM OLD.estado THEN
        INSERT INTO pedido_eventos(pedido_id, estado_anterior, estado_nuevo) VALUES (NEW.id, OLD.estado, NEW.estado);
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER pedido_evento AFTER INSERT OR UPDATE ON pedidos FOR EACH ROW EXECUTE FUNCTION pedido_registrar_evento();

CREATE FUNCTION detalle_proteger() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE pid bigint; estado_pedido varchar(20);
BEGIN
    IF TG_OP = 'DELETE' THEN pid := OLD.pedido_id; ELSE pid := NEW.pedido_id; END IF;
    IF TG_OP = 'UPDATE' AND NEW.pedido_id <> OLD.pedido_id THEN RAISE EXCEPTION 'No se traslada un detalle a otro pedido'; END IF;
    SELECT estado INTO estado_pedido FROM pedidos WHERE id = pid FOR UPDATE;
    IF estado_pedido IN ('ENTREGADO','CANCELADO') THEN RAISE EXCEPTION 'El detalle pertenece a un pedido finalizado'; END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    IF TG_OP = 'INSERT' THEN SELECT nombre INTO NEW.plato_nombre FROM platos WHERE id = NEW.plato_id; END IF;
    NEW.updated_at := localtimestamp;
    RETURN NEW;
END $$;
CREATE TRIGGER detalle_proteger BEFORE INSERT OR UPDATE OR DELETE ON pedido_detalles FOR EACH ROW EXECUTE FUNCTION detalle_proteger();

CREATE FUNCTION pago_validar() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE p pedidos%ROWTYPE; suma numeric;
BEGIN
    SELECT * INTO p FROM pedidos WHERE id = NEW.pedido_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Pedido inexistente'; END IF;
    IF p.estado <> 'TERMINADO' THEN RAISE EXCEPTION 'El pedido no esta listo para cobrar'; END IF;
    SELECT coalesce(sum(subtotal),0) INTO suma FROM pedido_detalles WHERE pedido_id = p.id;
    IF NEW.monto <> p.total OR p.total <> suma + p.costo_envio - p.descuento THEN
        RAISE EXCEPTION 'El pago no coincide con el detalle y total del pedido';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER pago_validar BEFORE INSERT ON pagos FOR EACH ROW EXECUTE FUNCTION pago_validar();

CREATE FUNCTION pago_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'No se edita ni elimina un pago confirmado; implementar reversos auditables'; END $$;
CREATE TRIGGER pago_inmutable BEFORE UPDATE OR DELETE ON pagos FOR EACH ROW EXECUTE FUNCTION pago_inmutable();

CREATE FUNCTION resena_validar() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pedidos p JOIN pagos pa ON pa.pedido_id = p.id
                   WHERE p.id = NEW.pedido_id AND p.cliente_id = NEW.cliente_id) THEN
        RAISE EXCEPTION 'Solo el cliente del pedido pagado puede resenarlo';
    END IF;
    IF NEW.plato_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pedido_detalles WHERE pedido_id = NEW.pedido_id AND plato_id = NEW.plato_id) THEN
        RAISE EXCEPTION 'El plato no pertenece a ese pedido';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END $$;
CREATE TRIGGER resena_validar BEFORE INSERT OR UPDATE ON resenas FOR EACH ROW EXECUTE FUNCTION resena_validar();

-- Cerrar por defecto el acceso directo de navegadores/roles publicos.
-- No se crean politicas permisivas. El escritorio requiere un rol backend privado
-- con permisos explicitos; propietario/BYPASSRLS puede operar. Nunca usarlo en JS web.
DO $$
DECLARE t text; r text;
BEGIN
    FOREACH t IN ARRAY ARRAY['categorias','usuarios','mesas','clientes','clientes_identidades',
        'clientes_direcciones','clientes_tokens','platos','platos_imagenes','pedidos',
        'pedido_detalles','pagos','pagos_intentos','pedidos_entregas','pedido_eventos','resenas','resenas_imagenes'] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC', t);
        FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
                EXECUTE format('REVOKE ALL ON TABLE public.%I FROM %I', t, r);
            END IF;
        END LOOP;
    END LOOP;
END $$;

-- Carta proporcionada por el usuario: 6 categorias, 99 productos.
-- SOLO para esquema nuevo. No borra pedidos, pagos ni carta existente.
SET LOCAL search_path = public;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM categorias) OR EXISTS (SELECT 1 FROM platos) THEN
        RAISE EXCEPTION 'La carta no esta vacia. No ejecutar este seed sobre datos existentes';
    END IF;
END $$;
INSERT INTO categorias (nombre, descripcion) VALUES
('Alitas', 'Alitas de pollo apanadas o a la parrilla, por cantidad de piezas'),
('Makis', 'Rollos de sushi, por cantidad de piezas'),
('Hamburguesas', 'Hamburguesas simples y dobles'),
('Pizzas', 'Pizzas artesanales por tamano'),
('Broaster', 'Pollo broaster por presa y combos'),
('Bebidas', 'Gaseosas, refrescos y bebidas frias');

-- =============================================
-- 4. ALITAS
-- Sabores: BBQ, Picante Buffalo, Miel Mostaza, Parmesano Ajo,
--          Broaster Natural, Mango Habanero
-- Tamanos: x6, x12, x24, x50
-- =============================================
INSERT INTO platos (nombre, descripcion, precio, categoria_id, tiempo_preparacion, disponible) VALUES
-- BBQ
('Alitas BBQ x6',  'Alitas bañadas en salsa BBQ, 6 piezas', 18.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 15, true),
('Alitas BBQ x12', 'Alitas bañadas en salsa BBQ, 12 piezas', 34.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 18, true),
('Alitas BBQ x24', 'Alitas bañadas en salsa BBQ, 24 piezas', 66.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 22, true),
('Alitas BBQ x50', 'Alitas bañadas en salsa BBQ, 50 piezas (para compartir)', 130.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 30, true),
-- Picante Buffalo
('Alitas Picante Buffalo x6',  'Alitas en salsa buffalo picante, 6 piezas', 18.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 15, true),
('Alitas Picante Buffalo x12', 'Alitas en salsa buffalo picante, 12 piezas', 34.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 18, true),
('Alitas Picante Buffalo x24', 'Alitas en salsa buffalo picante, 24 piezas', 66.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 22, true),
('Alitas Picante Buffalo x50', 'Alitas en salsa buffalo picante, 50 piezas (para compartir)', 130.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 30, true),
-- Miel Mostaza
('Alitas Miel Mostaza x6',  'Alitas en salsa de miel y mostaza, 6 piezas', 18.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 15, true),
('Alitas Miel Mostaza x12', 'Alitas en salsa de miel y mostaza, 12 piezas', 34.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 18, true),
('Alitas Miel Mostaza x24', 'Alitas en salsa de miel y mostaza, 24 piezas', 66.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 22, true),
('Alitas Miel Mostaza x50', 'Alitas en salsa de miel y mostaza, 50 piezas (para compartir)', 130.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 30, true),
-- Parmesano Ajo
('Alitas Parmesano Ajo x6',  'Alitas bañadas en salsa de parmesano y ajo, 6 piezas', 19.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 15, true),
('Alitas Parmesano Ajo x12', 'Alitas bañadas en salsa de parmesano y ajo, 12 piezas', 36.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 18, true),
('Alitas Parmesano Ajo x24', 'Alitas bañadas en salsa de parmesano y ajo, 24 piezas', 70.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 22, true),
('Alitas Parmesano Ajo x50', 'Alitas bañadas en salsa de parmesano y ajo, 50 piezas (para compartir)', 138.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 30, true),
-- Broaster Natural (apanada, sin salsa)
('Alitas Broaster Natural x6',  'Alitas apanadas estilo broaster, 6 piezas', 17.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 15, true),
('Alitas Broaster Natural x12', 'Alitas apanadas estilo broaster, 12 piezas', 32.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 18, true),
('Alitas Broaster Natural x24', 'Alitas apanadas estilo broaster, 24 piezas', 62.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 22, true),
('Alitas Broaster Natural x50', 'Alitas apanadas estilo broaster, 50 piezas (para compartir)', 122.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 30, true),
-- Mango Habanero
('Alitas Mango Habanero x6',  'Alitas en salsa de mango con habanero, 6 piezas', 19.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 15, true),
('Alitas Mango Habanero x12', 'Alitas en salsa de mango con habanero, 12 piezas', 36.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 18, true),
('Alitas Mango Habanero x24', 'Alitas en salsa de mango con habanero, 24 piezas', 70.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 22, true),
('Alitas Mango Habanero x50', 'Alitas en salsa de mango con habanero, 50 piezas (para compartir)', 138.00, (SELECT id FROM categorias WHERE nombre='Alitas'), 30, true);

-- =============================================
-- 5. MAKIS
-- Tipos: California, Acevichado, Crispy, Tempura, Filadelfia
-- Tamanos: x10, x20, x30, x40
-- =============================================
INSERT INTO platos (nombre, descripcion, precio, categoria_id, tiempo_preparacion, disponible) VALUES
-- California
('Maki California x10', 'Maki california (palta, kanikama, pepino), 10 piezas', 20.00, (SELECT id FROM categorias WHERE nombre='Makis'), 15, true),
('Maki California x20', 'Maki california (palta, kanikama, pepino), 20 piezas', 38.00, (SELECT id FROM categorias WHERE nombre='Makis'), 20, true),
('Maki California x30', 'Maki california (palta, kanikama, pepino), 30 piezas', 54.00, (SELECT id FROM categorias WHERE nombre='Makis'), 25, true),
('Maki California x40', 'Maki california (palta, kanikama, pepino), 40 piezas', 70.00, (SELECT id FROM categorias WHERE nombre='Makis'), 30, true),
-- Acevichado
('Maki Acevichado x10', 'Maki bañado en salsa acevichada, 10 piezas', 22.00, (SELECT id FROM categorias WHERE nombre='Makis'), 15, true),
('Maki Acevichado x20', 'Maki bañado en salsa acevichada, 20 piezas', 42.00, (SELECT id FROM categorias WHERE nombre='Makis'), 20, true),
('Maki Acevichado x30', 'Maki bañado en salsa acevichada, 30 piezas', 60.00, (SELECT id FROM categorias WHERE nombre='Makis'), 25, true),
('Maki Acevichado x40', 'Maki bañado en salsa acevichada, 40 piezas', 78.00, (SELECT id FROM categorias WHERE nombre='Makis'), 30, true),
-- Crispy
('Maki Crispy x10', 'Maki apanado crocante, 10 piezas', 21.00, (SELECT id FROM categorias WHERE nombre='Makis'), 15, true),
('Maki Crispy x20', 'Maki apanado crocante, 20 piezas', 40.00, (SELECT id FROM categorias WHERE nombre='Makis'), 20, true),
('Maki Crispy x30', 'Maki apanado crocante, 30 piezas', 57.00, (SELECT id FROM categorias WHERE nombre='Makis'), 25, true),
('Maki Crispy x40', 'Maki apanado crocante, 40 piezas', 74.00, (SELECT id FROM categorias WHERE nombre='Makis'), 30, true),
-- Tempura
('Maki Tempura x10', 'Maki con camaron tempura, 10 piezas', 23.00, (SELECT id FROM categorias WHERE nombre='Makis'), 18, true),
('Maki Tempura x20', 'Maki con camaron tempura, 20 piezas', 44.00, (SELECT id FROM categorias WHERE nombre='Makis'), 22, true),
('Maki Tempura x30', 'Maki con camaron tempura, 30 piezas', 63.00, (SELECT id FROM categorias WHERE nombre='Makis'), 27, true),
('Maki Tempura x40', 'Maki con camaron tempura, 40 piezas', 82.00, (SELECT id FROM categorias WHERE nombre='Makis'), 32, true),
-- Filadelfia
('Maki Filadelfia x10', 'Maki con queso filadelfia, 10 piezas', 22.00, (SELECT id FROM categorias WHERE nombre='Makis'), 15, true),
('Maki Filadelfia x20', 'Maki con queso filadelfia, 20 piezas', 42.00, (SELECT id FROM categorias WHERE nombre='Makis'), 20, true),
('Maki Filadelfia x30', 'Maki con queso filadelfia, 30 piezas', 60.00, (SELECT id FROM categorias WHERE nombre='Makis'), 25, true),
('Maki Filadelfia x40', 'Maki con queso filadelfia, 40 piezas', 78.00, (SELECT id FROM categorias WHERE nombre='Makis'), 30, true);

-- =============================================
-- 6. HAMBURGUESAS
-- Tipos: Clasica, Doble Carne, BBQ Bacon, Cheddar Especial, Hawaiana
-- Tamanos: Simple / Doble
-- =============================================
INSERT INTO platos (nombre, descripcion, precio, categoria_id, tiempo_preparacion, disponible) VALUES
('Hamburguesa Clasica Simple', 'Carne, lechuga, tomate, cebolla y salsas de la casa', 15.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 12, true),
('Hamburguesa Clasica Doble', 'Doble carne, lechuga, tomate, cebolla y salsas de la casa', 22.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 14, true),
('Hamburguesa BBQ Bacon Simple', 'Carne, tocino, queso cheddar y salsa BBQ', 19.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 14, true),
('Hamburguesa BBQ Bacon Doble', 'Doble carne, tocino, queso cheddar y salsa BBQ', 27.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 16, true),
('Hamburguesa Cheddar Especial Simple', 'Carne, doble queso cheddar y cebolla caramelizada', 18.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 13, true),
('Hamburguesa Cheddar Especial Doble', 'Doble carne, doble queso cheddar y cebolla caramelizada', 25.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 15, true),
('Hamburguesa Hawaiana Simple', 'Carne, piña grillada, jamon y queso', 17.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 13, true),
('Hamburguesa Hawaiana Doble', 'Doble carne, piña grillada, jamon y queso', 24.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 15, true),
('Hamburguesa Vegetariana', 'Hamburguesa de vegetales, lechuga, tomate y palta', 17.00, (SELECT id FROM categorias WHERE nombre='Hamburguesas'), 13, true);

-- =============================================
-- 7. PIZZAS
-- Sabores: Americana, Hawaiana, Pepperoni, Vegetariana,
--          Cuatro Quesos, Especial de la Casa
-- Tamanos: Personal, Mediana, Grande, Familiar
-- =============================================
INSERT INTO platos (nombre, descripcion, precio, categoria_id, tiempo_preparacion, disponible) VALUES
-- Americana
('Pizza Americana Personal', 'Jamon, salchicha y queso mozzarella - tamaño personal', 15.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 18, true),
('Pizza Americana Mediana',  'Jamon, salchicha y queso mozzarella - tamaño mediano', 25.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 20, true),
('Pizza Americana Grande',   'Jamon, salchicha y queso mozzarella - tamaño grande', 35.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 22, true),
('Pizza Americana Familiar', 'Jamon, salchicha y queso mozzarella - tamaño familiar', 45.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 25, true),
-- Hawaiana
('Pizza Hawaiana Personal', 'Jamon, piña y queso mozzarella - tamaño personal', 15.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 18, true),
('Pizza Hawaiana Mediana',  'Jamon, piña y queso mozzarella - tamaño mediano', 25.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 20, true),
('Pizza Hawaiana Grande',   'Jamon, piña y queso mozzarella - tamaño grande', 35.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 22, true),
('Pizza Hawaiana Familiar', 'Jamon, piña y queso mozzarella - tamaño familiar', 45.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 25, true),
-- Pepperoni
('Pizza Pepperoni Personal', 'Pepperoni y queso mozzarella - tamaño personal', 16.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 18, true),
('Pizza Pepperoni Mediana',  'Pepperoni y queso mozzarella - tamaño mediano', 27.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 20, true),
('Pizza Pepperoni Grande',   'Pepperoni y queso mozzarella - tamaño grande', 38.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 22, true),
('Pizza Pepperoni Familiar', 'Pepperoni y queso mozzarella - tamaño familiar', 49.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 25, true),
-- Vegetariana
('Pizza Vegetariana Personal', 'Pimiento, champiñon, cebolla, aceituna y mozzarella - tamaño personal', 15.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 18, true),
('Pizza Vegetariana Mediana',  'Pimiento, champiñon, cebolla, aceituna y mozzarella - tamaño mediano', 25.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 20, true),
('Pizza Vegetariana Grande',   'Pimiento, champiñon, cebolla, aceituna y mozzarella - tamaño grande', 35.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 22, true),
('Pizza Vegetariana Familiar', 'Pimiento, champiñon, cebolla, aceituna y mozzarella - tamaño familiar', 45.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 25, true),
-- Cuatro Quesos
('Pizza Cuatro Quesos Personal', 'Mozzarella, parmesano, queso azul y edam - tamaño personal', 17.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 18, true),
('Pizza Cuatro Quesos Mediana',  'Mozzarella, parmesano, queso azul y edam - tamaño mediano', 29.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 20, true),
('Pizza Cuatro Quesos Grande',   'Mozzarella, parmesano, queso azul y edam - tamaño grande', 41.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 22, true),
('Pizza Cuatro Quesos Familiar', 'Mozzarella, parmesano, queso azul y edam - tamaño familiar', 53.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 25, true),
-- Especial de la Casa
('Pizza Especial de la Casa Personal', 'Combinado de carnes, vegetales y mozzarella - tamaño personal', 18.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 20, true),
('Pizza Especial de la Casa Mediana',  'Combinado de carnes, vegetales y mozzarella - tamaño mediano', 30.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 22, true),
('Pizza Especial de la Casa Grande',   'Combinado de carnes, vegetales y mozzarella - tamaño grande', 42.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 24, true),
('Pizza Especial de la Casa Familiar', 'Combinado de carnes, vegetales y mozzarella - tamaño familiar', 55.00, (SELECT id FROM categorias WHERE nombre='Pizzas'), 27, true);

-- =============================================
-- 8. BROASTER
-- Por presa: Pierna, Pecho, Encuentro, Ala
-- Combos: 2, 4 (familiar) y 8 (balde) presas con papas
-- =============================================
INSERT INTO platos (nombre, descripcion, precio, categoria_id, tiempo_preparacion, disponible) VALUES
('Broaster 1 Presa - Pierna',    '1 presa de pierna apanada estilo broaster', 14.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 15, true),
('Broaster 1 Presa - Pecho',     '1 presa de pecho apanada estilo broaster', 15.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 15, true),
('Broaster 1 Presa - Encuentro', '1 presa de encuentro apanada estilo broaster', 14.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 15, true),
('Broaster 1 Presa - Ala',       '1 presa de ala apanada estilo broaster', 10.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 12, true),
('Broaster 2 Presas + Papas',    'Combo de 2 presas a elegir con papas fritas y ensalada', 26.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 18, true),
('Broaster 4 Presas Familiar + Papas', 'Combo familiar de 4 presas con papas fritas y ensalada', 48.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 22, true),
('Broaster 8 Presas Balde + Papas',    'Balde de 8 presas con papas fritas y ensalada, para compartir', 90.00, (SELECT id FROM categorias WHERE nombre='Broaster'), 28, true);

-- =============================================
-- 9. BEBIDAS
-- Gaseosas, chicha morada, limonada (normal y frozen),
-- refresco de maracuya, agua, cerveza
-- =============================================
INSERT INTO platos (nombre, descripcion, precio, categoria_id, tiempo_preparacion, disponible) VALUES
-- Gaseosas personales
('Gaseosa Inca Kola Personal', 'Botella personal 500ml', 6.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 2, true),
('Gaseosa Coca Cola Personal', 'Botella personal 500ml', 6.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 2, true),
('Gaseosa Pepsi Personal',     'Botella personal 500ml', 6.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 2, true),
('Gaseosa Guarana Personal',   'Botella personal 500ml', 6.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 2, true),
-- Gaseosas 1.5L
('Gaseosa Inca Kola 1.5L', 'Botella familiar 1.5 litros', 12.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 2, true),
('Gaseosa Coca Cola 1.5L', 'Botella familiar 1.5 litros', 12.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 2, true),
-- Chicha morada
('Chicha Morada Vaso',   'Vaso de chicha morada casera', 5.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 3, true),
('Jarra de Chicha Morada 1L', 'Jarra de chicha morada casera, 1 litro', 15.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 4, true),
-- Limonada
('Limonada Vaso',        'Vaso de limonada clasica', 5.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 3, true),
('Jarra de Limonada 1L', 'Jarra de limonada clasica, 1 litro', 15.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 4, true),
('Limonada Frozen Vaso', 'Limonada frozen (frappe), vaso', 8.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 5, true),
-- Refresco de maracuya
('Refresco de Maracuya Vaso',   'Vaso de refresco de maracuya', 5.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 3, true),
('Jarra de Maracuya 1L',        'Jarra de refresco de maracuya, 1 litro', 15.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 4, true),
-- Otras
('Agua Mineral Personal', 'Botella de agua mineral 500ml, con o sin gas', 4.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 1, true),
('Cerveza Personal',      'Botella de cerveza personal', 10.00, (SELECT id FROM categorias WHERE nombre='Bebidas'), 1, true);

-- =============================================
-- 10. VERIFICACION
-- =============================================
SELECT c.nombre AS categoria, COUNT(p.id) AS cantidad_platos
FROM categorias c
LEFT JOIN platos p ON p.categoria_id = c.id
GROUP BY c.nombre
ORDER BY c.nombre;

SELECT nombre, precio, disponible FROM platos ORDER BY categoria_id, precio;



COMMIT;

