-- LA FONDA - INSTALACION NUEVA, PostgreSQL 14+.
-- Ejecutar en una base VACIA / proyecto Supabase NUEVO. No es una migracion.
-- No elimina datos. Si existe una tabla homonima, falla y revierte la transaccion.
-- No crea usuarios PostgreSQL ni contiene contrasenas o claves de Supabase.
BEGIN;
SET LOCAL search_path = public;
SET LOCAL TIME ZONE 'America/Lima';

CREATE TABLE categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) NOT NULL UNIQUE CHECK (btrim(nombre) <> ''),
    descripcion varchar(255), activo boolean NOT NULL DEFAULT true,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT localtimestamp
);
CREATE UNIQUE INDEX uq_categoria_nombre_ci ON categorias (lower(btrim(nombre)));

CREATE TABLE usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni varchar(8) NOT NULL UNIQUE CHECK (dni ~ '^[0-9]{8}$'),
    nombre varchar(255) NOT NULL CHECK (length(btrim(nombre)) BETWEEN 1 AND 100),
    apellido varchar(255) NOT NULL CHECK (length(btrim(apellido)) BETWEEN 1 AND 100),
    email varchar(255),
    password varchar(255), -- Solo hash BCrypt; NULL para MOZO.
    rol varchar(255) NOT NULL CHECK (rol IN ('MOZO','CAJERO','ADMIN','COCINERO')),
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp,
    CONSTRAINT ck_usuario_email CHECK (email IS NULL OR (length(email) <= 254 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$')),
    CONSTRAINT ck_usuario_clave_rol CHECK (
        (rol = 'MOZO' AND password IS NULL) OR
        (rol <> 'MOZO' AND password IS NOT NULL AND password ~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$')
    )
);
CREATE UNIQUE INDEX uq_usuario_email_ci ON usuarios (lower(btrim(email))) WHERE email IS NOT NULL;

CREATE TABLE mesas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero integer NOT NULL UNIQUE CHECK (numero > 0),
    capacidad integer NOT NULL DEFAULT 4 CHECK (capacidad BETWEEN 1 AND 100),
    estado varchar(255) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado IN ('DISPONIBLE','OCUPADA','RESERVADA')),
    created_at timestamp NOT NULL DEFAULT localtimestamp
);

CREATE TABLE clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(255) NOT NULL CHECK (btrim(nombre) <> ''),
    apellido varchar(255) NOT NULL CHECK (btrim(apellido) <> ''),
    email varchar(255) NOT NULL CHECK (length(email) <= 254 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'),
    password varchar(255), -- Hash local, nunca la clave de Gmail. NULL con OAuth.
    telefono varchar(255), direccion_default varchar(255),
    activo boolean NOT NULL DEFAULT true,
    email_verificado_at timestamptz,
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp,
    CONSTRAINT ck_cliente_hash CHECK (password IS NULL OR password ~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$')
);
CREATE UNIQUE INDEX uq_cliente_email_ci ON clientes (lower(btrim(email)));

CREATE TABLE clientes_identidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    proveedor varchar(30) NOT NULL CHECK (proveedor IN ('GOOGLE','SUPABASE')),
    sujeto varchar(255) NOT NULL CHECK (btrim(sujeto) <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (proveedor, sujeto), UNIQUE (cliente_id, proveedor)
);
CREATE TABLE clientes_direcciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    etiqueta varchar(50) NOT NULL DEFAULT 'Casa',
    direccion text NOT NULL CHECK (btrim(direccion) <> ''),
    distrito varchar(100), referencia text,
    latitud numeric(9,6) CHECK (latitud BETWEEN -90 AND 90),
    longitud numeric(9,6) CHECK (longitud BETWEEN -180 AND 180),
    predeterminada boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_direccion_principal ON clientes_direcciones(cliente_id) WHERE predeterminada;
CREATE INDEX ix_direcciones_cliente ON clientes_direcciones(cliente_id);
CREATE TABLE clientes_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    tipo varchar(30) NOT NULL CHECK (tipo IN ('VERIFICAR_EMAIL','RECUPERAR_CLAVE','SESION')),
    token_hash varchar(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    expires_at timestamptz NOT NULL, used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX ix_tokens_cliente ON clientes_tokens(cliente_id);
CREATE INDEX ix_tokens_expiracion ON clientes_tokens(expires_at);

CREATE TABLE platos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(255) NOT NULL CHECK (btrim(nombre) <> ''),
    descripcion varchar(255),
    precio numeric(10,2) NOT NULL CHECK (precio > 0),
    categoria_id bigint NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
    tiempo_preparacion integer CHECK (tiempo_preparacion >= 0),
    disponible boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp
);
CREATE UNIQUE INDEX uq_plato_categoria_nombre_ci ON platos(categoria_id, lower(btrim(nombre)));
CREATE INDEX ix_platos_carta ON platos(categoria_id, disponible);
CREATE TABLE platos_imagenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plato_id bigint NOT NULL REFERENCES platos(id) ON DELETE CASCADE,
    storage_key text NOT NULL CHECK (btrim(storage_key) <> ''),
    url_publica text CHECK (url_publica IS NULL OR url_publica LIKE 'https://%'),
    alt_text varchar(255), orden integer NOT NULL DEFAULT 0,
    principal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (plato_id, storage_key)
);
CREATE INDEX ix_imagenes_plato ON platos_imagenes(plato_id);
CREATE UNIQUE INDEX uq_imagen_principal ON platos_imagenes(plato_id) WHERE principal;

CREATE TABLE pedidos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(20) NOT NULL UNIQUE,
    tipo varchar(20) NOT NULL DEFAULT 'LOCAL' CHECK (tipo IN ('LOCAL','DELIVERY','RECOJO')),
    origen varchar(20) NOT NULL DEFAULT 'PRESENCIAL' CHECK (origen IN ('PRESENCIAL','WEB')),
    mesa_id bigint REFERENCES mesas(id) ON DELETE RESTRICT,
    usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
    cliente_id bigint REFERENCES clientes(id) ON DELETE RESTRICT,
    cliente_nombre varchar(255), cliente_telefono varchar(20), direccion_entrega varchar(255),
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_PROCESO','LISTO','TERMINADO','ENTREGADO','CANCELADO')),
    subtotal numeric(38,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0), -- Base SIN IGV.
    total numeric(38,2) NOT NULL DEFAULT 0 CHECK (total >= 0), -- Total final CON IGV.
    igv numeric(38,2) NOT NULL DEFAULT 0 CHECK (igv >= 0),
    tasa_igv numeric(5,4) NOT NULL DEFAULT 0.18 CHECK (tasa_igv BETWEEN 0 AND 1),
    costo_envio numeric(10,2) NOT NULL DEFAULT 0 CHECK (costo_envio >= 0),
    descuento numeric(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    observacion_extra varchar(255), cerrado boolean NOT NULL DEFAULT false,
    mesa_numero integer, mozo_nombre varchar(255), -- Instantaneas de identificacion.
    clave_idempotencia uuid UNIQUE, -- El futuro backend debe enviar una clave estable por intento de pedido web.
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp,
    fecha_cierre timestamp,
    CONSTRAINT ck_pedido_local CHECK (tipo <> 'LOCAL' OR mesa_id IS NOT NULL),
    CONSTRAINT ck_pedido_web CHECK (origen <> 'WEB' OR (cliente_id IS NOT NULL AND clave_idempotencia IS NOT NULL AND tipo IN ('DELIVERY','RECOJO'))),
    CONSTRAINT ck_delivery_direccion CHECK (tipo <> 'DELIVERY' OR (direccion_entrega IS NOT NULL AND btrim(direccion_entrega) <> ''))
);
CREATE INDEX ix_pedidos_mesa_estado ON pedidos(mesa_id, estado);
CREATE INDEX ix_pedidos_cocina ON pedidos(estado, created_at);
CREATE INDEX ix_pedidos_cliente ON pedidos(cliente_id, created_at DESC);
CREATE INDEX ix_pedidos_usuario ON pedidos(usuario_id);
CREATE UNIQUE INDEX uq_mesa_pedido_abierto ON pedidos(mesa_id)
    WHERE mesa_id IS NOT NULL AND estado IN ('PENDIENTE','EN_PROCESO','LISTO','TERMINADO');

CREATE TABLE pedido_detalles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    plato_id bigint NOT NULL REFERENCES platos(id) ON DELETE RESTRICT,
    cantidad integer NOT NULL CHECK (cantidad > 0),
    precio_unitario numeric(10,2) NOT NULL CHECK (precio_unitario > 0),
    subtotal numeric(10,2) NOT NULL CHECK (subtotal = round(cantidad * precio_unitario, 2)),
    plato_nombre varchar(255), -- Instantanea; no se lee el precio actual al reimprimir.
    observacion_extra varchar(255),
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_PROCESO','LISTO','ENTREGADO','CANCELADO')),
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    updated_at timestamp NOT NULL DEFAULT localtimestamp
);
CREATE INDEX ix_detalles_pedido ON pedido_detalles(pedido_id);
CREATE INDEX ix_detalles_plato ON pedido_detalles(plato_id);

CREATE TABLE pagos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL UNIQUE REFERENCES pedidos(id) ON DELETE RESTRICT,
    monto numeric(10,2) NOT NULL CHECK (monto > 0),
    metodo varchar(20) NOT NULL CHECK (metodo IN ('EFECTIVO','TARJETA','YAPE','TRANSFERENCIA','OTRO','ONLINE')),
    referencia varchar(50),
    usuario_id bigint REFERENCES usuarios(id) ON DELETE RESTRICT,
    proveedor varchar(50), transaccion_externa varchar(255),
    created_at timestamp NOT NULL DEFAULT localtimestamp,
    UNIQUE(proveedor, transaccion_externa)
);
CREATE INDEX ix_pagos_fecha ON pagos(created_at DESC);
CREATE INDEX ix_pagos_cajero ON pagos(usuario_id);
CREATE TABLE pagos_intentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    proveedor varchar(50) NOT NULL, referencia_externa varchar(255),
    clave_idempotencia uuid NOT NULL UNIQUE,
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','APROBADO','RECHAZADO','EXPIRADO')),
    monto numeric(10,2) NOT NULL CHECK (monto > 0), moneda char(3) NOT NULL DEFAULT 'PEN',
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (proveedor, referencia_externa)
);
CREATE INDEX ix_intentos_pedido ON pagos_intentos(pedido_id);
CREATE TABLE pedidos_entregas (
    pedido_id bigint PRIMARY KEY REFERENCES pedidos(id) ON DELETE RESTRICT,
    estado varchar(25) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','PREPARANDO','LISTO','EN_CAMINO','ENTREGADO','CANCELADO')),
    direccion_snapshot text, receptor varchar(150), telefono varchar(30),
    programado_para timestamptz, entregado_at timestamptz,
    instrucciones text, updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE pedido_eventos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    estado_anterior varchar(20), estado_nuevo varchar(20) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_eventos_pedido ON pedido_eventos(pedido_id, created_at);

CREATE TABLE resenas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
    pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    plato_id bigint REFERENCES platos(id) ON DELETE RESTRICT,
    calificacion smallint NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario text CHECK (length(comentario) <= 3000),
    estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','PUBLICADA','OCULTA')),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_resena_pedido ON resenas(cliente_id, pedido_id) WHERE plato_id IS NULL;
CREATE UNIQUE INDEX uq_resena_plato ON resenas(cliente_id, pedido_id, plato_id) WHERE plato_id IS NOT NULL;
CREATE INDEX ix_resenas_publicadas ON resenas(plato_id, estado);
CREATE INDEX ix_resenas_pedido ON resenas(pedido_id);
CREATE TABLE resenas_imagenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resena_id bigint NOT NULL REFERENCES resenas(id) ON DELETE CASCADE,
    storage_key text NOT NULL, alt_text varchar(255),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_resena_imagenes ON resenas_imagenes(resena_id);

-- Normalizacion y auditoria compatibles con los LocalDateTime actuales de Java.
CREATE FUNCTION normalizar_persona() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.email := nullif(lower(btrim(NEW.email)), '');
    NEW.updated_at := localtimestamp;
    RETURN NEW;
END $$;
CREATE TRIGGER usuarios_normalizar BEFORE INSERT OR UPDATE ON usuarios FOR EACH ROW EXECUTE FUNCTION normalizar_persona();
CREATE TRIGGER clientes_normalizar BEFORE INSERT OR UPDATE ON clientes FOR EACH ROW EXECUTE FUNCTION normalizar_persona();

CREATE FUNCTION pedido_preparar() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.estado IN ('ENTREGADO','CANCELADO') THEN
        RAISE EXCEPTION 'Un pedido finalizado no se modifica';
    END IF;
    NEW.subtotal := round(NEW.total / (1 + NEW.tasa_igv), 2);
    NEW.igv := NEW.total - NEW.subtotal;
    NEW.updated_at := localtimestamp;
    IF TG_OP = 'INSERT' THEN
        IF NEW.mesa_id IS NOT NULL THEN SELECT numero INTO NEW.mesa_numero FROM mesas WHERE id = NEW.mesa_id; END IF;
        IF NEW.usuario_id IS NOT NULL THEN SELECT nombre || ' ' || apellido INTO NEW.mozo_nombre FROM usuarios WHERE id = NEW.usuario_id; END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER pedido_preparar BEFORE INSERT OR UPDATE ON pedidos FOR EACH ROW EXECUTE FUNCTION pedido_preparar();

CREATE FUNCTION pedido_registrar_evento() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO pedido_eventos(pedido_id, estado_nuevo) VALUES (NEW.id, NEW.estado);
    ELSIF NEW.estado IS DISTINCT FROM OLD.estado THEN
        INSERT INTO pedido_eventos(pedido_id, estado_anterior, estado_nuevo) VALUES (NEW.id, OLD.estado, NEW.estado);
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER pedido_evento AFTER INSERT OR UPDATE ON pedidos FOR EACH ROW EXECUTE FUNCTION pedido_registrar_evento();

CREATE FUNCTION detalle_proteger() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE pid bigint; estado_pedido varchar(20);
BEGIN
    IF TG_OP = 'DELETE' THEN pid := OLD.pedido_id; ELSE pid := NEW.pedido_id; END IF;
    IF TG_OP = 'UPDATE' AND NEW.pedido_id <> OLD.pedido_id THEN RAISE EXCEPTION 'No se traslada un detalle a otro pedido'; END IF;
    SELECT estado INTO estado_pedido FROM pedidos WHERE id = pid FOR UPDATE;
    IF estado_pedido IN ('ENTREGADO','CANCELADO') THEN RAISE EXCEPTION 'El detalle pertenece a un pedido finalizado'; END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    IF TG_OP = 'INSERT' THEN SELECT nombre INTO NEW.plato_nombre FROM platos WHERE id = NEW.plato_id; END IF;
    NEW.updated_at := localtimestamp;
    RETURN NEW;
END $$;
CREATE TRIGGER detalle_proteger BEFORE INSERT OR UPDATE OR DELETE ON pedido_detalles FOR EACH ROW EXECUTE FUNCTION detalle_proteger();

CREATE FUNCTION pago_validar() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE p pedidos%ROWTYPE; suma numeric;
BEGIN
    SELECT * INTO p FROM pedidos WHERE id = NEW.pedido_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Pedido inexistente'; END IF;
    IF p.estado <> 'TERMINADO' THEN RAISE EXCEPTION 'El pedido no esta listo para cobrar'; END IF;
    SELECT coalesce(sum(subtotal),0) INTO suma FROM pedido_detalles WHERE pedido_id = p.id;
    IF NEW.monto <> p.total OR p.total <> suma + p.costo_envio - p.descuento THEN
        RAISE EXCEPTION 'El pago no coincide con el detalle y total del pedido';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER pago_validar BEFORE INSERT ON pagos FOR EACH ROW EXECUTE FUNCTION pago_validar();

CREATE FUNCTION pago_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'No se edita ni elimina un pago confirmado; implementar reversos auditables'; END $$;
CREATE TRIGGER pago_inmutable BEFORE UPDATE OR DELETE ON pagos FOR EACH ROW EXECUTE FUNCTION pago_inmutable();

CREATE FUNCTION resena_validar() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pedidos p JOIN pagos pa ON pa.pedido_id = p.id
                   WHERE p.id = NEW.pedido_id AND p.cliente_id = NEW.cliente_id) THEN
        RAISE EXCEPTION 'Solo el cliente del pedido pagado puede resenarlo';
    END IF;
    IF NEW.plato_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pedido_detalles WHERE pedido_id = NEW.pedido_id AND plato_id = NEW.plato_id) THEN
        RAISE EXCEPTION 'El plato no pertenece a ese pedido';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END $$;
CREATE TRIGGER resena_validar BEFORE INSERT OR UPDATE ON resenas FOR EACH ROW EXECUTE FUNCTION resena_validar();

-- Cerrar por defecto el acceso directo de navegadores/roles publicos.
-- No se crean politicas permisivas. El escritorio requiere un rol backend privado
-- con permisos explicitos; propietario/BYPASSRLS puede operar. Nunca usarlo en JS web.
DO $$
DECLARE t text; r text;
BEGIN
    FOREACH t IN ARRAY ARRAY['categorias','usuarios','mesas','clientes','clientes_identidades',
        'clientes_direcciones','clientes_tokens','platos','platos_imagenes','pedidos',
        'pedido_detalles','pagos','pagos_intentos','pedidos_entregas','pedido_eventos','resenas','resenas_imagenes'] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC', t);
        FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
                EXECUTE format('REVOKE ALL ON TABLE public.%I FROM %I', t, r);
            END IF;
        END LOOP;
    END LOOP;
END $$;
COMMIT;
