-- =============================================================
-- LA FONDA - MIGRACION DE INVENTARIO, PROVEEDORES Y REPORTES
-- Compatible con la BD existente. NO elimina tablas ni ventas.
-- Ejecutar UNA VEZ sobre la base compartida desktop/web.
-- =============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.proveedores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc varchar(11) UNIQUE,
    nombre varchar(150) NOT NULL CHECK (btrim(nombre) <> ''),
    telefono varchar(30),
    email varchar(254),
    direccion text,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (ruc IS NULL OR ruc ~ '^[0-9]{11}$')
);

CREATE TABLE IF NOT EXISTS public.ingredientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL UNIQUE CHECK (btrim(nombre) <> ''),
    categoria varchar(80),
    unidad_base varchar(20) NOT NULL CHECK (unidad_base IN ('UNIDAD','GRAMO','MILILITRO')),
    stock_actual numeric(14,3) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    stock_minimo numeric(14,3) NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    costo_promedio numeric(14,6) NOT NULL DEFAULT 0 CHECK (costo_promedio >= 0),
    activo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.proveedor_ingredientes (
    proveedor_id bigint NOT NULL REFERENCES public.proveedores(id) ON DELETE CASCADE,
    ingrediente_id bigint NOT NULL REFERENCES public.ingredientes(id) ON DELETE CASCADE,
    precio_referencia numeric(12,2) NOT NULL CHECK (precio_referencia >= 0),
    cantidad_referencia numeric(14,3) NOT NULL DEFAULT 1 CHECK (cantidad_referencia > 0),
    unidad_compra varchar(30),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (proveedor_id, ingrediente_id)
);

CREATE TABLE IF NOT EXISTS public.compras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id bigint NOT NULL REFERENCES public.proveedores(id),
    usuario_id bigint REFERENCES public.usuarios(id),
    numero_documento varchar(60),
    fecha timestamptz NOT NULL DEFAULT now(),
    subtotal numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    igv numeric(12,2) NOT NULL DEFAULT 0 CHECK (igv >= 0),
    total numeric(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    observacion text,
    estado varchar(20) NOT NULL DEFAULT 'REGISTRADA' CHECK (estado IN ('REGISTRADA','ANULADA')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.compra_detalles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id bigint NOT NULL REFERENCES public.compras(id) ON DELETE CASCADE,
    ingrediente_id bigint NOT NULL REFERENCES public.ingredientes(id),
    cantidad_compra numeric(14,3),
    unidad_compra varchar(20),
    cantidad_base numeric(14,3) NOT NULL CHECK (cantidad_base > 0),
    costo_total numeric(12,2) NOT NULL CHECK (costo_total >= 0),
    costo_unitario_base numeric(14,6) NOT NULL CHECK (costo_unitario_base >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.compra_detalles ADD COLUMN IF NOT EXISTS cantidad_compra numeric(14,3);
ALTER TABLE public.compra_detalles ADD COLUMN IF NOT EXISTS unidad_compra varchar(20);

CREATE TABLE IF NOT EXISTS public.plato_ingredientes (
    plato_id bigint NOT NULL REFERENCES public.platos(id) ON DELETE CASCADE,
    ingrediente_id bigint NOT NULL REFERENCES public.ingredientes(id) ON DELETE RESTRICT,
    cantidad_base numeric(14,3) NOT NULL CHECK (cantidad_base > 0),
    PRIMARY KEY (plato_id, ingrediente_id)
);

CREATE TABLE IF NOT EXISTS public.plato_stock_diario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plato_id bigint NOT NULL REFERENCES public.platos(id) ON DELETE CASCADE,
    fecha date NOT NULL,
    stock_inicial integer NOT NULL CHECK (stock_inicial >= 0),
    stock_actual integer NOT NULL CHECK (stock_actual >= 0),
    activo boolean NOT NULL DEFAULT true,
    inventario_reservado boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (plato_id, fecha)
);

ALTER TABLE public.plato_stock_diario ADD COLUMN IF NOT EXISTS inventario_reservado boolean NOT NULL DEFAULT false;


-- -------------------------------------------------------------
-- Familias de platos / presentaciones.
-- Ej.: "Makis acevichados" -> x6, x12, x24.
-- Cada variante sigue siendo un registro normal de public.platos,
-- por lo que pedido_detalles, cocina, caja y reportes NO cambian.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.plato_familias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL CHECK (btrim(nombre) <> ''),
    descripcion varchar(255),
    categoria_id bigint NOT NULL REFERENCES public.categorias(id) ON DELETE RESTRICT,
    activo boolean NOT NULL DEFAULT true,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_plato_familias_categoria_nombre
ON public.plato_familias(categoria_id, lower(nombre));

CREATE TABLE IF NOT EXISTS public.plato_familia_variantes (
    familia_id bigint NOT NULL REFERENCES public.plato_familias(id) ON DELETE CASCADE,
    plato_id bigint NOT NULL UNIQUE REFERENCES public.platos(id) ON DELETE CASCADE,
    etiqueta varchar(80) NOT NULL CHECK (btrim(etiqueta) <> ''),
    orden integer NOT NULL DEFAULT 0,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (familia_id, plato_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_plato_familia_etiqueta
ON public.plato_familia_variantes(familia_id, lower(etiqueta));

CREATE INDEX IF NOT EXISTS ix_plato_familias_categoria
ON public.plato_familias(categoria_id, activo, orden);

CREATE INDEX IF NOT EXISTS ix_plato_familia_variantes_familia
ON public.plato_familia_variantes(familia_id, activo, orden);

CREATE OR REPLACE VIEW public.vw_platos_opciones AS
SELECT
    f.id AS familia_id,
    f.nombre AS familia_nombre,
    f.descripcion AS familia_descripcion,
    f.categoria_id,
    f.activo AS familia_activa,
    fv.plato_id,
    fv.etiqueta,
    fv.orden AS variante_orden,
    fv.activo AS variante_activa,
    p.nombre AS plato_nombre,
    p.descripcion AS plato_descripcion,
    p.precio,
    p.tiempo_preparacion,
    p.disponible
FROM public.plato_familias f
JOIN public.plato_familia_variantes fv ON fv.familia_id = f.id
JOIN public.platos p ON p.id = fv.plato_id;

CREATE TABLE IF NOT EXISTS public.inventario_movimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingrediente_id bigint NOT NULL REFERENCES public.ingredientes(id),
    tipo varchar(30) NOT NULL CHECK (tipo IN (
        'ENTRADA_COMPRA','SALIDA_VENTA','DEVOLUCION_CANCELACION',
        'AJUSTE_ENTRADA','AJUSTE_SALIDA','MERMA','DEVOLUCION_PROVEEDOR'
    )),
    cantidad numeric(14,3) NOT NULL CHECK (cantidad > 0),
    stock_anterior numeric(14,3) NOT NULL,
    stock_nuevo numeric(14,3) NOT NULL,
    pedido_detalle_id bigint REFERENCES public.pedido_detalles(id) ON DELETE SET NULL,
    compra_detalle_id bigint REFERENCES public.compra_detalles(id) ON DELETE SET NULL,
    motivo text,
    reversado boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.plato_stock_movimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plato_stock_id bigint NOT NULL REFERENCES public.plato_stock_diario(id) ON DELETE CASCADE,
    pedido_detalle_id bigint REFERENCES public.pedido_detalles(id) ON DELETE SET NULL,
    tipo varchar(30) NOT NULL CHECK (tipo IN ('SALIDA_VENTA','DEVOLUCION_CANCELACION','AJUSTE_ENTRADA','AJUSTE_SALIDA')),
    cantidad integer NOT NULL CHECK (cantidad > 0),
    stock_anterior integer NOT NULL,
    stock_nuevo integer NOT NULL,
    reversado boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mermas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingrediente_id bigint NOT NULL REFERENCES public.ingredientes(id),
    usuario_id bigint REFERENCES public.usuarios(id),
    cantidad numeric(14,3) NOT NULL CHECK (cantidad > 0),
    motivo varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.gastos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint REFERENCES public.usuarios(id),
    categoria varchar(80) NOT NULL,
    descripcion varchar(255) NOT NULL,
    monto numeric(12,2) NOT NULL CHECK (monto > 0),
    fecha timestamptz NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.caja_cierres (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint REFERENCES public.usuarios(id),
    fecha_inicio timestamptz NOT NULL,
    fecha_fin timestamptz NOT NULL,
    efectivo numeric(12,2) NOT NULL DEFAULT 0,
    tarjeta numeric(12,2) NOT NULL DEFAULT 0,
    yape numeric(12,2) NOT NULL DEFAULT 0,
    transferencia numeric(12,2) NOT NULL DEFAULT 0,
    online numeric(12,2) NOT NULL DEFAULT 0,
    otros numeric(12,2) NOT NULL DEFAULT 0,
    total_sistema numeric(12,2) NOT NULL DEFAULT 0,
    total_contado numeric(12,2),
    diferencia numeric(12,2),
    observacion text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS ix_ingredientes_categoria ON public.ingredientes(categoria);
CREATE INDEX IF NOT EXISTS ix_movimientos_ingrediente_fecha ON public.inventario_movimientos(ingrediente_id, created_at);
CREATE INDEX IF NOT EXISTS ix_movimientos_pedido_detalle ON public.inventario_movimientos(pedido_detalle_id);
CREATE INDEX IF NOT EXISTS ix_compra_fecha ON public.compras(fecha);
CREATE INDEX IF NOT EXISTS ix_gastos_fecha ON public.gastos(fecha);
CREATE INDEX IF NOT EXISTS ix_stock_diario_fecha ON public.plato_stock_diario(fecha, plato_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_inv_salida_detalle_ingrediente
ON public.inventario_movimientos(pedido_detalle_id, ingrediente_id)
WHERE tipo = 'SALIDA_VENTA' AND pedido_detalle_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_stock_salida_detalle
ON public.plato_stock_movimientos(pedido_detalle_id)
WHERE tipo = 'SALIDA_VENTA' AND pedido_detalle_id IS NOT NULL;

-- -------------------------------------------------------------
-- Vista: stock vendible HOY.
-- Regla operativa: cada día empieza en 0. Si no existe fila de stock
-- para hoy, el plato NO se puede vender. La receta se consume al
-- habilitar/preparar stock, no nuevamente al vender.
-- -------------------------------------------------------------
CREATE OR REPLACE VIEW public.vw_platos_stock_hoy AS
SELECT p.id AS plato_id,
       COALESCE(d.stock_actual, 0)::integer AS stock_diario,
       COALESCE(d.stock_actual, 0)::integer AS stock_disponible
FROM public.platos p
LEFT JOIN public.plato_stock_diario d
  ON d.plato_id = p.id
 AND d.fecha = (now() AT TIME ZONE 'America/Lima')::date
 AND d.activo;

-- Configurar el stock diario equivale a habilitar/preparar porciones.
-- Al AUMENTAR porciones se descuentan los ingredientes de receta.
-- Al REDUCIR porciones no vendidas se devuelven al almacén.
-- Insumos generales no incluidos en la receta (ej. aceite de freidora)
-- se controlan con ajuste manual.
CREATE OR REPLACE FUNCTION public.configurar_stock_diario(
    p_plato_id bigint, p_fecha date, p_stock_inicial integer
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_hoy date := (now() AT TIME ZONE 'America/Lima')::date;
    v_anterior_inicial integer := 0;
    v_anterior_actual integer := 0;
    v_vendido integer := 0;
    v_delta integer := 0;
    v_nuevo_actual integer := 0;
    v_reservado boolean := false;
    v_rec record;
    v_stock numeric(14,3);
    v_requerido numeric(14,3);
BEGIN
    IF p_fecha IS NULL THEN p_fecha := v_hoy; END IF;
    IF p_fecha <> v_hoy THEN
        RAISE EXCEPTION 'El stock operativo solo se configura para hoy (%)', v_hoy;
    END IF;
    IF p_stock_inicial IS NULL OR p_stock_inicial < 0 THEN
        RAISE EXCEPTION 'El stock inicial debe ser 0 o mayor';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM platos WHERE id = p_plato_id AND disponible) THEN
        RAISE EXCEPTION 'El plato no existe o está deshabilitado';
    END IF;

    SELECT stock_inicial, stock_actual, inventario_reservado
      INTO v_anterior_inicial, v_anterior_actual, v_reservado
      FROM plato_stock_diario
     WHERE plato_id = p_plato_id AND fecha = p_fecha
     FOR UPDATE;
    IF NOT FOUND THEN
        v_anterior_inicial := 0; v_anterior_actual := 0; v_reservado := true;
    END IF;

    v_vendido := GREATEST(v_anterior_inicial - v_anterior_actual, 0);
    IF p_stock_inicial < v_vendido THEN
        RAISE EXCEPTION 'No puedes bajar el stock inicial por debajo de lo ya vendido (% porciones)', v_vendido;
    END IF;
    v_nuevo_actual := p_stock_inicial - v_vendido;
    -- Filas creadas por la versión anterior no tenían reserva de receta.
    -- En su primera edición reservamos solo las porciones que siguen sin vender.
    v_delta := CASE WHEN v_reservado THEN p_stock_inicial - v_anterior_inicial ELSE v_nuevo_actual END;

    -- Bloqueo en orden estable para evitar carreras entre administradores.
    FOR v_rec IN
        SELECT pi.ingrediente_id, pi.cantidad_base, i.nombre, i.activo
          FROM plato_ingredientes pi
          JOIN ingredientes i ON i.id = pi.ingrediente_id
         WHERE pi.plato_id = p_plato_id
         ORDER BY pi.ingrediente_id
    LOOP
        IF NOT v_rec.activo THEN
            RAISE EXCEPTION 'Ingrediente % está inactivo', v_rec.nombre;
        END IF;
        SELECT stock_actual INTO v_stock FROM ingredientes WHERE id=v_rec.ingrediente_id FOR UPDATE;
        v_requerido := v_rec.cantidad_base * abs(v_delta);
        IF v_delta > 0 THEN
            IF v_stock < v_requerido THEN
                RAISE EXCEPTION 'No alcanza %: disponible %, requerido % para habilitar % porciones adicionales',
                    v_rec.nombre, v_stock, v_requerido, v_delta;
            END IF;
            UPDATE ingredientes SET stock_actual=stock_actual-v_requerido, updated_at=now() WHERE id=v_rec.ingrediente_id;
            INSERT INTO inventario_movimientos(ingrediente_id,tipo,cantidad,stock_anterior,stock_nuevo,motivo)
            VALUES(v_rec.ingrediente_id,'AJUSTE_SALIDA',v_requerido,v_stock,v_stock-v_requerido,
                   'Producción diaria / habilitación de stock del plato '||p_plato_id);
        ELSIF v_delta < 0 THEN
            UPDATE ingredientes SET stock_actual=stock_actual+v_requerido, updated_at=now() WHERE id=v_rec.ingrediente_id;
            INSERT INTO inventario_movimientos(ingrediente_id,tipo,cantidad,stock_anterior,stock_nuevo,motivo)
            VALUES(v_rec.ingrediente_id,'AJUSTE_ENTRADA',v_requerido,v_stock,v_stock+v_requerido,
                   'Reducción de producción diaria del plato '||p_plato_id);
        END IF;
    END LOOP;

    INSERT INTO plato_stock_diario(plato_id,fecha,stock_inicial,stock_actual,activo,inventario_reservado,updated_at)
    VALUES(p_plato_id,p_fecha,p_stock_inicial,v_nuevo_actual,true,true,now())
    ON CONFLICT(plato_id,fecha) DO UPDATE SET
        stock_inicial=excluded.stock_inicial, stock_actual=excluded.stock_actual, activo=true, inventario_reservado=true, updated_at=now();
    RETURN v_nuevo_actual;
END;
$$;

-- -------------------------------------------------------------
-- Compra: cada detalle aumenta inventario y recalcula costo medio.
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_compra_detalle_ingresa_stock()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_anterior numeric(14,3);
    v_nuevo numeric(14,3);
    v_costo_anterior numeric(14,6);
    v_costo_nuevo numeric(14,6);
    v_proveedor bigint;
BEGIN
    SELECT stock_actual, costo_promedio
      INTO v_anterior, v_costo_anterior
      FROM ingredientes
     WHERE id = NEW.ingrediente_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Ingrediente % no existe', NEW.ingrediente_id;
    END IF;

    v_nuevo := v_anterior + NEW.cantidad_base;
    IF v_nuevo > 0 THEN
        v_costo_nuevo := ((v_anterior * v_costo_anterior) + NEW.costo_total) / v_nuevo;
    ELSE
        v_costo_nuevo := NEW.costo_unitario_base;
    END IF;

    UPDATE ingredientes
       SET stock_actual = v_nuevo,
           costo_promedio = ROUND(v_costo_nuevo, 6),
           updated_at = now()
     WHERE id = NEW.ingrediente_id;

    INSERT INTO inventario_movimientos(
        ingrediente_id, tipo, cantidad, stock_anterior, stock_nuevo,
        compra_detalle_id, motivo
    ) VALUES (
        NEW.ingrediente_id, 'ENTRADA_COMPRA', NEW.cantidad_base,
        v_anterior, v_nuevo, NEW.id, 'Compra registrada'
    );

    SELECT proveedor_id INTO v_proveedor FROM compras WHERE id = NEW.compra_id;
    INSERT INTO proveedor_ingredientes(
        proveedor_id, ingrediente_id, precio_referencia, cantidad_referencia, unidad_compra, updated_at
    ) VALUES (
        v_proveedor, NEW.ingrediente_id, NEW.costo_total, COALESCE(NEW.cantidad_compra, NEW.cantidad_base),
        COALESCE(NEW.unidad_compra, (SELECT unidad_base FROM ingredientes WHERE id = NEW.ingrediente_id)), now()
    )
    ON CONFLICT (proveedor_id, ingrediente_id) DO UPDATE SET
        precio_referencia = EXCLUDED.precio_referencia,
        cantidad_referencia = EXCLUDED.cantidad_referencia,
        unidad_compra = EXCLUDED.unidad_compra,
        updated_at = now();

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_compra_detalle_ingresa_stock ON public.compra_detalles;
CREATE TRIGGER trg_compra_detalle_ingresa_stock
AFTER INSERT ON public.compra_detalles
FOR EACH ROW EXECUTE FUNCTION public.fn_compra_detalle_ingresa_stock();

-- -------------------------------------------------------------
-- Venta: descuenta SOLO las porciones del stock diario.
-- Los ingredientes ya fueron consumidos/reservados cuando el admin
-- habilitó esas porciones mediante configurar_stock_diario().
-- Sin stock configurado hoy => venta bloqueada (incluye web).
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_pedido_detalle_descontar_stock()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_stock_id bigint;
    v_stock_actual integer;
    v_fecha date := (now() AT TIME ZONE 'America/Lima')::date;
BEGIN
    IF NEW.estado = 'CANCELADO' THEN RETURN NEW; END IF;

    SELECT id, stock_actual INTO v_stock_id, v_stock_actual
      FROM plato_stock_diario
     WHERE plato_id=NEW.plato_id AND fecha=v_fecha AND activo
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El plato % no tiene stock habilitado para hoy', NEW.plato_id;
    END IF;
    IF v_stock_actual < NEW.cantidad THEN
        RAISE EXCEPTION 'Stock diario insuficiente para el plato %. Disponible: %, solicitado: %',
            NEW.plato_id, v_stock_actual, NEW.cantidad;
    END IF;

    UPDATE plato_stock_diario SET stock_actual=stock_actual-NEW.cantidad, updated_at=now() WHERE id=v_stock_id;
    INSERT INTO plato_stock_movimientos(plato_stock_id,pedido_detalle_id,tipo,cantidad,stock_anterior,stock_nuevo)
    VALUES(v_stock_id,NEW.id,'SALIDA_VENTA',NEW.cantidad,v_stock_actual,v_stock_actual-NEW.cantidad);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedido_detalle_descontar_stock ON public.pedido_detalles;
CREATE TRIGGER trg_pedido_detalle_descontar_stock
AFTER INSERT ON public.pedido_detalles
FOR EACH ROW EXECUTE FUNCTION public.fn_pedido_detalle_descontar_stock();

-- -------------------------------------------------------------
-- Cancelación de un detalle: repone exactamente lo descontado.
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_pedido_detalle_reponer_stock()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_mov record;
    v_anterior numeric(14,3);
    v_stock_mov record;
    v_stock_anterior integer;
BEGIN
    IF OLD.estado <> 'CANCELADO' AND NEW.estado = 'CANCELADO' THEN
        FOR v_mov IN
            SELECT * FROM inventario_movimientos
             WHERE pedido_detalle_id = NEW.id
               AND tipo = 'SALIDA_VENTA'
               AND NOT reversado
             ORDER BY id
             FOR UPDATE
        LOOP
            SELECT stock_actual INTO v_anterior
              FROM ingredientes
             WHERE id = v_mov.ingrediente_id
             FOR UPDATE;

            UPDATE ingredientes
               SET stock_actual = stock_actual + v_mov.cantidad,
                   updated_at = now()
             WHERE id = v_mov.ingrediente_id;

            INSERT INTO inventario_movimientos(
                ingrediente_id, tipo, cantidad, stock_anterior, stock_nuevo,
                pedido_detalle_id, motivo
            ) VALUES (
                v_mov.ingrediente_id, 'DEVOLUCION_CANCELACION', v_mov.cantidad,
                v_anterior, v_anterior + v_mov.cantidad, NEW.id,
                'Reposición por cancelación de pedido'
            );

            UPDATE inventario_movimientos SET reversado = true WHERE id = v_mov.id;
        END LOOP;

        FOR v_stock_mov IN
            SELECT * FROM plato_stock_movimientos
             WHERE pedido_detalle_id = NEW.id
               AND tipo = 'SALIDA_VENTA'
               AND NOT reversado
             ORDER BY id
             FOR UPDATE
        LOOP
            SELECT stock_actual INTO v_stock_anterior
              FROM plato_stock_diario
             WHERE id = v_stock_mov.plato_stock_id
             FOR UPDATE;

            UPDATE plato_stock_diario
               SET stock_actual = stock_actual + v_stock_mov.cantidad,
                   updated_at = now()
             WHERE id = v_stock_mov.plato_stock_id;

            INSERT INTO plato_stock_movimientos(
                plato_stock_id, pedido_detalle_id, tipo, cantidad,
                stock_anterior, stock_nuevo
            ) VALUES (
                v_stock_mov.plato_stock_id, NEW.id, 'DEVOLUCION_CANCELACION',
                v_stock_mov.cantidad, v_stock_anterior,
                v_stock_anterior + v_stock_mov.cantidad
            );

            UPDATE plato_stock_movimientos SET reversado = true WHERE id = v_stock_mov.id;
        END LOOP;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedido_detalle_reponer_stock ON public.pedido_detalles;
CREATE TRIGGER trg_pedido_detalle_reponer_stock
AFTER UPDATE OF estado ON public.pedido_detalles
FOR EACH ROW EXECUTE FUNCTION public.fn_pedido_detalle_reponer_stock();

-- Cancelar cabecera cancela sus detalles y activa la reposición anterior.
CREATE OR REPLACE FUNCTION public.fn_pedido_cancelado_propagar_detalles()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF OLD.estado <> 'CANCELADO' AND NEW.estado = 'CANCELADO' THEN
        UPDATE pedido_detalles
           SET estado = 'CANCELADO', updated_at = LOCALTIMESTAMP
         WHERE pedido_id = NEW.id
           AND estado <> 'CANCELADO';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedido_cancelado_propagar_detalles ON public.pedidos;
-- IMPORTANTE: BEFORE, no AFTER. La BD original protege los detalles de pedidos
-- ya CANCELADOS; propagarlos antes del cambio de cabecera permite que el trigger
-- detalle_proteger los acepte y que después se reponga el stock correctamente.
CREATE TRIGGER trg_pedido_cancelado_propagar_detalles
BEFORE UPDATE OF estado ON public.pedidos
FOR EACH ROW EXECUTE FUNCTION public.fn_pedido_cancelado_propagar_detalles();

-- Función segura para ajuste manual desde el escritorio.
CREATE OR REPLACE FUNCTION public.ajustar_stock_ingrediente(
    p_ingrediente_id bigint,
    p_delta numeric,
    p_motivo text
) RETURNS numeric
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_anterior numeric(14,3);
    v_nuevo numeric(14,3);
    v_tipo varchar(30);
BEGIN
    IF p_delta = 0 THEN
        RAISE EXCEPTION 'El ajuste no puede ser cero';
    END IF;

    SELECT stock_actual INTO v_anterior
      FROM ingredientes
     WHERE id = p_ingrediente_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Ingrediente no existe';
    END IF;

    v_nuevo := v_anterior + p_delta;
    IF v_nuevo < 0 THEN
        RAISE EXCEPTION 'El ajuste dejaría stock negativo. Stock actual: %', v_anterior;
    END IF;

    v_tipo := CASE WHEN p_delta > 0 THEN 'AJUSTE_ENTRADA' ELSE 'AJUSTE_SALIDA' END;

    UPDATE ingredientes
       SET stock_actual = v_nuevo, updated_at = now()
     WHERE id = p_ingrediente_id;

    INSERT INTO inventario_movimientos(
        ingrediente_id, tipo, cantidad, stock_anterior, stock_nuevo, motivo
    ) VALUES (
        p_ingrediente_id, v_tipo, abs(p_delta), v_anterior, v_nuevo, p_motivo
    );

    RETURN v_nuevo;
END;
$$;

-- -------------------------------------------------------------
-- Seguridad: los módulos nuevos son administrativos/backend.
-- No se exponen directamente a anon/authenticated.
-- -------------------------------------------------------------
DO $$
DECLARE t text; r text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'proveedores','ingredientes','proveedor_ingredientes','compras','compra_detalles',
        'plato_ingredientes','plato_stock_diario','plato_familias','plato_familia_variantes',
        'inventario_movimientos','plato_stock_movimientos','mermas','gastos','caja_cierres'
    ] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC', t);
        FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
                EXECUTE format('REVOKE ALL ON TABLE public.%I FROM %I', t, r);
            END IF;
        END LOOP;
    END LOOP;
END $$;

REVOKE ALL ON TABLE public.vw_platos_stock_hoy FROM PUBLIC;
REVOKE ALL ON TABLE public.vw_platos_opciones FROM PUBLIC;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE public.vw_platos_stock_hoy FROM anon;
        REVOKE ALL ON TABLE public.vw_platos_opciones FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE public.vw_platos_stock_hoy FROM authenticated;
        REVOKE ALL ON TABLE public.vw_platos_opciones FROM authenticated;
    END IF;
END $$;

REVOKE ALL ON FUNCTION public.configurar_stock_diario(bigint, date, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ajustar_stock_ingrediente(bigint, numeric, text) FROM PUBLIC;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON FUNCTION public.ajustar_stock_ingrediente(bigint, numeric, text) FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON FUNCTION public.ajustar_stock_ingrediente(bigint, numeric, text) FROM authenticated;
    END IF;
END $$;

COMMIT;

-- Vista mínima y segura para que el backend/web pueda consultar disponibilidad
-- sin exponer costos, proveedores ni movimientos internos.
CREATE OR REPLACE VIEW public.vw_carta_stock_publico AS
SELECT p.id AS plato_id,
       p.disponible AS habilitado_catalogo,
       COALESCE(v.stock_disponible,0) AS stock_hoy,
       (p.disponible AND COALESCE(v.stock_disponible,0) > 0) AS disponible_hoy
FROM public.platos p
LEFT JOIN public.vw_platos_stock_hoy v ON v.plato_id=p.id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
        GRANT SELECT ON public.vw_carta_stock_publico TO anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
        GRANT SELECT ON public.vw_carta_stock_publico TO authenticated;
    END IF;
END $$;
